.TH "_ps_font_info" 3 "Tue May 13 2025" "Version 2.8" "Picasso API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_ps_font_info \- A structure that contains font information\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <picasso\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float \fBsize\fP"
.br
.ti -1c
.RI "float \fBascent\fP"
.br
.ti -1c
.RI "float \fBdescent\fP"
.br
.ti -1c
.RI "float \fBleading\fP"
.br
.ti -1c
.RI "uint32_t \fBunitsEM\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A structure that contains font information\&. 
.PP
Definition at line 2126 of file picasso\&.h\&.
.SH "Field Documentation"
.PP 
.SS "float _ps_font_info::ascent"
Ascent, maximum distance above the baseline\&. 
.PP
Definition at line 2134 of file picasso\&.h\&.
.SS "float _ps_font_info::descent"
Descent, maximum distance below the baseline\&. 
.PP
Definition at line 2138 of file picasso\&.h\&.
.SS "float _ps_font_info::leading"
Leading, the spaceing between consecutive lines of text\&. 
.PP
Definition at line 2142 of file picasso\&.h\&.
.SS "float _ps_font_info::size"
Size, the height of glyph\&. 
.PP
Definition at line 2130 of file picasso\&.h\&.
.SS "uint32_t _ps_font_info::unitsEM"
UnitsEm, the number of glyph space units per em\&. 
.PP
Definition at line 2146 of file picasso\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Picasso API from the source code\&.
