.TH "_ps_memory_funcs" 3 "Thu Apr 2 2026" "Version 2.9" "Picasso API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_ps_memory_funcs \- Memory allocator functions structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <picasso_backport\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBps_free_func\fP \fBmem_free\fP"
.br
.ti -1c
.RI "\fBps_calloc_func\fP \fBmem_calloc\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Memory allocator functions structure\&. 
.PP
Definition at line 63 of file picasso_backport\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBps_calloc_func\fP _ps_memory_funcs::mem_calloc"
Memory free function 
.PP
Definition at line 66 of file picasso_backport\&.h\&.
.SS "\fBps_free_func\fP _ps_memory_funcs::mem_free"
Memory allocation function 
.PP
Definition at line 65 of file picasso_backport\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Picasso API from the source code\&.
