.TH "_ps_point" 3 "Tue Dec 24 2024" "Version 2.8" "Picasso API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_ps_point \- A structure that contains a point in a two-dimensional coordinate system\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <picasso\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A structure that contains a point in a two-dimensional coordinate system\&. 
.PP
Definition at line 202 of file picasso\&.h\&.
.SH "Field Documentation"
.PP 
.SS "float _ps_point::x"
the x coordinate of the point\&. 
.PP
Definition at line 204 of file picasso\&.h\&.
.SS "float _ps_point::y"
the y coordinate of the point\&. 
.PP
Definition at line 206 of file picasso\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Picasso API from the source code\&.
