.TH "_ps_size" 3 "Tue May 13 2025" "Version 2.8" "Picasso API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_ps_size \- A structure that contains width and height values\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <picasso\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float \fBw\fP"
.br
.ti -1c
.RI "float \fBh\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A structure that contains width and height values\&. 
.PP
Definition at line 178 of file picasso\&.h\&.
.SH "Field Documentation"
.PP 
.SS "float _ps_size::h"
height value\&. 
.PP
Definition at line 182 of file picasso\&.h\&.
.SS "float _ps_size::w"
width value\&. 
.PP
Definition at line 180 of file picasso\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Picasso API from the source code\&.
