.TH "_ps_glyph" 3 "Tue May 13 2025" "Version 2.8" "Picasso API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_ps_glyph \- A character glyph of a font\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <picasso\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void * \fBglyph\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A character glyph of a font\&. 
.PP
Definition at line 170 of file picasso\&.h\&.
.SH "Field Documentation"
.PP 
.SS "void* _ps_glyph::glyph"
private glyph data\&. 
.PP
Definition at line 172 of file picasso\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Picasso API from the source code\&.
