.TH "_ps_color" 3 "Tue Dec 24 2024" "Version 2.8" "Picasso API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_ps_color \- A structure that contains rgba values for a color\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <picasso\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float \fBr\fP"
.br
.ti -1c
.RI "float \fBg\fP"
.br
.ti -1c
.RI "float \fBb\fP"
.br
.ti -1c
.RI "float \fBa\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A structure that contains rgba values for a color\&. 
.PP
Definition at line 212 of file picasso\&.h\&.
.SH "Field Documentation"
.PP 
.SS "float _ps_color::a"
the alpha component for a color (0 ~ 1)\&. 
.PP
Definition at line 220 of file picasso\&.h\&.
.SS "float _ps_color::b"
the blue component for a color (0 ~ 1)\&. 
.PP
Definition at line 218 of file picasso\&.h\&.
.SS "float _ps_color::g"
the green component for a color (0 ~ 1)\&. 
.PP
Definition at line 216 of file picasso\&.h\&.
.SS "float _ps_color::r"
the red component for a color (0 ~ 1)\&. 
.PP
Definition at line 214 of file picasso\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Picasso API from the source code\&.
