.TH "_ps_rect" 3 "Tue Dec 24 2024" "Version 2.8" "Picasso API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_ps_rect \- A structure that contains location and dimensions of a rectangle\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <picasso\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.ti -1c
.RI "float \fBw\fP"
.br
.ti -1c
.RI "float \fBh\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A structure that contains location and dimensions of a rectangle\&. 
.PP
Definition at line 188 of file picasso\&.h\&.
.SH "Field Documentation"
.PP 
.SS "float _ps_rect::h"
the height of the rectangle\&. 
.PP
Definition at line 196 of file picasso\&.h\&.
.SS "float _ps_rect::w"
the width of the rectangle\&. 
.PP
Definition at line 194 of file picasso\&.h\&.
.SS "float _ps_rect::x"
locate left of the rectangle\&. 
.PP
Definition at line 190 of file picasso\&.h\&.
.SS "float _ps_rect::y"
locate top of the rectangle\&. 
.PP
Definition at line 192 of file picasso\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Picasso API from the source code\&.
