.TH "_psx_image" 3 "Tue May 13 2025" "Version 2.8" "Picasso API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_psx_image \- A image object\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <psx_image\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBwidth\fP"
.br
.ti -1c
.RI "int \fBheight\fP"
.br
.ti -1c
.RI "int \fBpitch\fP"
.br
.ti -1c
.RI "\fBps_color_format\fP \fBformat\fP"
.br
.ti -1c
.RI "\fBpsx_image_frame\fP * \fBframes\fP"
.br
.ti -1c
.RI "size_t \fBnum_frames\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A image object\&. 
.PP
Definition at line 60 of file psx_image\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBps_color_format\fP _psx_image::format"
image format 
.PP
Definition at line 68 of file psx_image\&.h\&.
.SS "\fBpsx_image_frame\fP* _psx_image::frames"
image data frames 
.PP
Definition at line 70 of file psx_image\&.h\&.
.SS "int _psx_image::height"
image height 
.PP
Definition at line 64 of file psx_image\&.h\&.
.SS "size_t _psx_image::num_frames"
number of frame 
.PP
Definition at line 72 of file psx_image\&.h\&.
.SS "int _psx_image::pitch"
bytes of a scanline 
.PP
Definition at line 66 of file psx_image\&.h\&.
.SS "int _psx_image::width"
image width 
.PP
Definition at line 62 of file psx_image\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Picasso API from the source code\&.
