.TH "_psx_image_frame" 3 "Tue Dec 24 2024" "Version 2.8" "Picasso API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_psx_image_frame \- A frame image data\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <psx_image\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBps_image\fP * \fBimg\fP"
.br
.ti -1c
.RI "\fBps_byte\fP * \fBdata\fP"
.br
.ti -1c
.RI "size_t \fBsize\fP"
.br
.ti -1c
.RI "int \fBduration\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A frame image data\&. 
.PP
Definition at line 43 of file psx_image\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBps_byte\fP* _psx_image_frame::data"
image data buffer 
.PP
Definition at line 47 of file psx_image\&.h\&.
.SS "int _psx_image_frame::duration"
current frame duration (in milliseconds, 0 ignore) 
.PP
Definition at line 51 of file psx_image\&.h\&.
.SS "\fBps_image\fP* _psx_image_frame::img"
picasso image object wrap 
.PP
Definition at line 45 of file psx_image\&.h\&.
.SS "size_t _psx_image_frame::size"
sizeof image data in bytes 
.PP
Definition at line 49 of file psx_image\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Picasso API from the source code\&.
