.TH "data" 3 "Tue May 13 2025" "Version 2.8" "Picasso API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
data
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTrue\fP   1"
.br
.RI "define true value "
.ti -1c
.RI "#define \fBFalse\fP   0"
.br
.RI "define false value "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef int32_t \fBps_bool\fP"
.br
.RI "boolean type "
.ti -1c
.RI "typedef uint16_t \fBps_uchar16\fP"
.br
.RI "16 bit unsigned unicode character "
.ti -1c
.RI "typedef int16_t \fBps_schar16\fP"
.br
.RI "16 bit signed unicode character "
.ti -1c
.RI "typedef uint8_t \fBps_byte\fP"
.br
.RI "byte data type "
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define False   0"

.PP
define false value 
.PP
\fBSee also\fP
.RS 4
\fBTrue\fP 
.RE
.PP

.PP
Definition at line 74 of file picasso\&.h\&.
.SS "#define True   1"

.PP
define true value 
.PP
\fBSee also\fP
.RS 4
\fBFalse\fP 
.RE
.PP

.PP
Definition at line 67 of file picasso\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "\fBps_bool\fP"

.PP
boolean type 
.PP
\fBSee also\fP
.RS 4
\fBps_uchar16\fP, \fBps_schar16\fP, \fBps_byte\fP 
.RE
.PP

.PP
Definition at line 60 of file picasso\&.h\&.
.SS "\fBps_byte\fP"

.PP
byte data type 
.PP
\fBSee also\fP
.RS 4
\fBps_bool\fP, \fBps_uchar16\fP, \fBps_schar16\fP 
.RE
.PP

.PP
Definition at line 95 of file picasso\&.h\&.
.SS "\fBps_schar16\fP"

.PP
16 bit signed unicode character 
.PP
\fBSee also\fP
.RS 4
\fBps_bool\fP, \fBps_uchar16\fP, \fBps_byte\fP 
.RE
.PP

.PP
Definition at line 88 of file picasso\&.h\&.
.SS "\fBps_uchar16\fP"

.PP
16 bit unsigned unicode character 
.PP
\fBSee also\fP
.RS 4
\fBps_bool\fP, \fBps_schar16\fP, \fBps_byte\fP 
.RE
.PP

.PP
Definition at line 81 of file picasso\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Picasso API from the source code\&.
