.TH "drawing" 3 "Tue May 13 2025" "Version 2.8" "Picasso API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
drawing
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBFill\fP"
.br
.ti -1c
.RI "\fBStroke\fP"
.br
.ti -1c
.RI "\fBShadow\fP"
.br
.ti -1c
.RI "\fBAttribute\fP"
.br
.ti -1c
.RI "\fBPaint\fP"
.br
.ti -1c
.RI "\fBClip\fP"
.br
.ti -1c
.RI "\fBState\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for Picasso API from the source code\&.
