.TH "extimg" 3 "Tue Dec 24 2024" "Version 2.8" "Picasso API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extimg
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBXImage Object Types\fP"
.br
.ti -1c
.RI "\fBXImage Functions\fP"
.br
.ti -1c
.RI "\fBXImage Coders Register functions\fP"
.br
.ti -1c
.RI "\fBXImage Coders Plugin side functions\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for Picasso API from the source code\&.
