.TH "graphic" 3 "Tue Dec 24 2024" "Version 2.8" "Picasso API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
graphic
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBContext\fP"
.br
.ti -1c
.RI "\fBCanvas\fP"
.br
.ti -1c
.RI "\fBImage\fP"
.br
.ti -1c
.RI "\fBPattern\fP"
.br
.ti -1c
.RI "\fBGradient\fP"
.br
.ti -1c
.RI "\fBMask\fP"
.br
.ti -1c
.RI "\fBDrawing\fP"
.br
.ti -1c
.RI "\fBFont\fP"
.br
.ti -1c
.RI "\fBText\fP"
.br
.ti -1c
.RI "\fBTransform\fP"
.br
.ti -1c
.RI "\fBMatrix\fP"
.br
.ti -1c
.RI "\fBGeometry\fP"
.br
.ti -1c
.RI "\fBPath\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for Picasso API from the source code\&.
