.TH "include/picasso_ext.h" 3 "Tue May 13 2025" "Version 2.8" "Picasso API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/picasso_ext.h
.SH SYNOPSIS
.br
.PP
\fC#include 'picasso\&.h'\fP
.br

.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBpsx_result\fP { \fBS_OK\fP = 0, \fBS_BAD_PARAMS\fP = 1, \fBS_NOT_SUPPORT\fP = 2, \fBS_OUT_OF_MEMORY\fP = 3, \fBS_INIT_FAILURE\fP = 4, \fBS_FAILURE\fP = 5 }"
.br
.RI "Status code return by call APIs\&. "
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
Zhang Ji Peng onecoolx@gmail.com 
.RE
.PP
\fBDate\fP
.RS 4
2025/5/12
.RE
.PP
This file includes all common definitions for the picasso extension\&.
.PP
.PP
.nf
   Copyright (C) 2008 ~ 2025  Zhang Ji Peng

   All rights reserved.

   Picasso is a vector graphic library..fi
.PP
 
.PP
Definition in file \fBpicasso_ext\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Picasso API from the source code\&.
