.TH "svgtypes" 3 "Tue May 13 2025" "Version 2.8" "Picasso API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
svgtypes
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct _psx_svg \fBpsx_svg\fP"
.br
.RI "An opaque type represents an svg document\&. "
.ti -1c
.RI "typedef struct _psx_svg_render \fBpsx_svg_render\fP"
.br
.RI "An opaque type represents an svg render object\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SH "Typedef Documentation"
.PP 
.SS "\fBpsx_svg\fP"

.PP
An opaque type represents an svg document\&. 
.PP
\fBSee also\fP
.RS 4
\fBpsx_svg_render\fP 
.RE
.PP

.PP
Definition at line 48 of file psx_svg\&.h\&.
.SS "\fBpsx_svg_render\fP"

.PP
An opaque type represents an svg render object\&. 
.PP
\fBSee also\fP
.RS 4
\fBpsx_svg\fP 
.RE
.PP

.PP
Definition at line 55 of file psx_svg\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Picasso API from the source code\&.
