.TH "types" 3 "Tue May 13 2025" "Version 2.8" "Picasso API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
types
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fB_psx_image_frame\fP"
.br
.RI "A frame image data\&. "
.ti -1c
.RI "struct \fB_psx_image\fP"
.br
.RI "A image object\&. "
.ti -1c
.RI "struct \fB_psx_image_header\fP"
.br
.RI "Image reader header define\&. "
.ti -1c
.RI "struct \fB_psx_image_operator\fP"
.br
.RI "The image operator define\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBIMG_OBJ\fP(image)   \fBIMG_OBJ_AT_INDEX\fP(image, 0)"
.br
.RI "Get first ps_image obj\&. "
.ti -1c
.RI "#define \fBIMG_DATA\fP(image)   \fBIMG_DATA_AT_INDEX\fP(image, 0)"
.br
.RI "Get first image frame data\&. "
.ti -1c
.RI "#define \fBIMG_DATA_SIZE\fP(image)   \fBIMG_DATA_SIZE_AT_INDEX\fP(image, 0)"
.br
.RI "Get first image frame data size\&. "
.ti -1c
.RI "#define \fBIMG_OBJ_AT_INDEX\fP(image,  idx)   (image\->frames[idx]\&.img)"
.br
.RI "Get ps_image obj at index\&. "
.ti -1c
.RI "#define \fBIMG_DATA_AT_INDEX\fP(image,  idx)   (image\->frames[idx]\&.data)"
.br
.RI "Get image frame data at index\&. "
.ti -1c
.RI "#define \fBIMG_DATA_SIZE_AT_INDEX\fP(img,  idx)   (img\->frames[idx]\&.size)"
.br
.RI "Get image frame data size at index\&. "
.ti -1c
.RI "#define \fBIMG_DURATION_AT_INDEX\fP(img,  idx)   (img\->frames[idx]\&.duration)"
.br
.RI "Get image frame duration at index\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fB_psx_image_frame\fP \fBpsx_image_frame\fP"
.br
.RI "A frame image data\&. "
.ti -1c
.RI "typedef struct \fB_psx_image\fP \fBpsx_image\fP"
.br
.RI "A image object\&. "
.ti -1c
.RI "typedef struct \fB_psx_image_header\fP \fBpsx_image_header\fP"
.br
.RI "Image reader header define\&. "
.ti -1c
.RI "typedef struct \fB_psx_image_operator\fP \fBpsx_image_operator\fP"
.br
.RI "The image operator define\&. "
.ti -1c
.RI "typedef enum \fB_psx_priority_level\fP \fBpsx_priority_level\fP"
.br
.RI "Priority level for image_operator\&. "
.ti -1c
.RI "typedef struct _psx_svg \fBpsx_svg\fP"
.br
.RI "An opaque type represents an svg document\&. "
.ti -1c
.RI "typedef struct _psx_svg_render \fBpsx_svg_render\fP"
.br
.RI "An opaque type represents an svg render object\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fB_psx_priority_level\fP { \fBPRIORITY_EXTENTED\fP = -1, \fBPRIORITY_DEFAULT\fP = 0, \fBPRIORITY_MASTER\fP = 1 }"
.br
.RI "Priority level for image_operator\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define IMG_DATA(image)   \fBIMG_DATA_AT_INDEX\fP(image, 0)"

.PP
Get first image frame data\&. 
.PP
\fBSee also\fP
.RS 4
\fBIMG_DATA_AT_INDEX\fP 
.RE
.PP

.PP
Definition at line 87 of file psx_image\&.h\&.
.SS "#define IMG_DATA_AT_INDEX(image, idx)   (image\->frames[idx]\&.data)"

.PP
Get image frame data at index\&. 
.PP
\fBSee also\fP
.RS 4
\fBIMG_DATA\fP 
.RE
.PP

.PP
Definition at line 108 of file psx_image\&.h\&.
.SS "#define IMG_DATA_SIZE(image)   \fBIMG_DATA_SIZE_AT_INDEX\fP(image, 0)"

.PP
Get first image frame data size\&. 
.PP
\fBSee also\fP
.RS 4
\fBIMG_DATA_SIZE_AT_INDEX\fP 
.RE
.PP

.PP
Definition at line 94 of file psx_image\&.h\&.
.SS "#define IMG_DATA_SIZE_AT_INDEX(img, idx)   (img\->frames[idx]\&.size)"

.PP
Get image frame data size at index\&. 
.PP
\fBSee also\fP
.RS 4
\fBIMG_DATA_SIZE\fP 
.RE
.PP

.PP
Definition at line 115 of file psx_image\&.h\&.
.SS "#define IMG_DURATION_AT_INDEX(img, idx)   (img\->frames[idx]\&.duration)"

.PP
Get image frame duration at index\&. 
.PP
\fBSee also\fP
.RS 4
\fBIMG_DATA_SIZE\fP, \fBIMG_DATA\fP 
.RE
.PP

.PP
Definition at line 122 of file psx_image\&.h\&.
.SS "#define IMG_OBJ(image)   \fBIMG_OBJ_AT_INDEX\fP(image, 0)"

.PP
Get first ps_image obj\&. 
.PP
\fBSee also\fP
.RS 4
\fBIMG_OBJ_AT_INDEX\fP 
.RE
.PP

.PP
Definition at line 80 of file psx_image\&.h\&.
.SS "#define IMG_OBJ_AT_INDEX(image, idx)   (image\->frames[idx]\&.img)"

.PP
Get ps_image obj at index\&. 
.PP
\fBSee also\fP
.RS 4
\fBIMG_OBJ\fP 
.RE
.PP

.PP
Definition at line 101 of file psx_image\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fB_psx_image_operator\fP \fBpsx_image_operator\fP"

.PP
The image operator define\&. 
.PP
\fBSee also\fP
.RS 4
\fBpsx_image_register_operator\fP \fBpsx_image_unregister_operator\fP 
.RE
.PP

.SS "typedef enum \fB_psx_priority_level\fP \fBpsx_priority_level\fP"

.PP
Priority level for image_operator\&. 
.PP
\fBSee also\fP
.RS 4
\fBpsx_image_register_operator\fP 
.RE
.PP

.SS "\fBpsx_svg\fP"

.PP
An opaque type represents an svg document\&. 
.PP
\fBSee also\fP
.RS 4
\fBpsx_svg_render\fP 
.RE
.PP

.PP
Definition at line 48 of file psx_svg\&.h\&.
.SS "\fBpsx_svg_render\fP"

.PP
An opaque type represents an svg render object\&. 
.PP
\fBSee also\fP
.RS 4
\fBpsx_svg\fP 
.RE
.PP

.PP
Definition at line 55 of file psx_svg\&.h\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fB_psx_priority_level\fP"

.PP
Priority level for image_operator\&. 
.PP
\fBSee also\fP
.RS 4
\fBpsx_image_register_operator\fP 
.RE
.PP

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIPRIORITY_EXTENTED \fP\fP
Low level operator\&. 
.TP
\fB\fIPRIORITY_DEFAULT \fP\fP
Default level operator\&. 
.TP
\fB\fIPRIORITY_MASTER \fP\fP
High level operator\&. 
.PP
Definition at line 89 of file psx_image_plugin\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Picasso API from the source code\&.
