name: Ubuntu Linux Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup GTK2
      run: |
        sudo apt-get update --fix-missing
        sudo apt-get install libgtk2.0-dev
    - name: Generate Project
      run: ./build_linux.sh
    - name: make
      run: make -C ./proj
