name: WebAssembly / WASM build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install EMCC tools
      run: |
        sudo apt-get update --fix-missing
        sudo apt-get install emscripten
      
    - name: Build
      run: |
        emmake make -C ./wasm -f Makefile.em
        emcc --no-entry -s"ALLOW_MEMORY_GROWTH=1" -s"EXPORTED_FUNCTIONS=@export.list" -s"EXPORTED_RUNTIME_METHODS=@runtime.list" ./wasm/libpicasso.a -o ./wasm/picasso.wasm
        emmake make -C ./wasm -f Makefile.em clean
